### ISSUE TITLE
Getting an error when executing maven job

### ISSUE THREAD

**Issue by AnalogJ** [ikedam/backend-update-center2#18]
Hi,
I'm trying to use this script to generate the update-center.json file. I'm calling the maven job with the following command:

	mvn exec:java -Dexec.args="-id company-update-center \
	    -h /dev/null \
	    -o update-center.json \
	    -r release-history.json
	    -repository http://company-web-server/path-to-company-repository/ \
	    -hpiDirectory plugins \
	    -download download \
	    -nowiki \
	    -key company-jenkins-update-center.key \
	    -certificate company-jenkins-update-center.crt \
	    -root-certificate company-jenkins-update-center.crt
	" -X

And I'm getting this stacktrace:

	[INFO] ------------------------------------------------------------------------
	[INFO] BUILD FAILURE
	[INFO] ------------------------------------------------------------------------
	[INFO] Total time: 1.598 s
	[INFO] Finished at: 2014-11-25T00:21:24+00:00
	[INFO] Final Memory: 8M/80M
	[INFO] ------------------------------------------------------------------------
	[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2:java (default-cli) on project update-center2: An exception occured while executing the Java class. null: InvocationTargetException: NullPointerException -> [Help 1]
	org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2:java (default-cli) on project update-center2: An exception occured while executing the Java class. null
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
		at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
		at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
		at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
		at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
		at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
		at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
		at java.lang.reflect.Method.invoke(Method.java:597)
		at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
		at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
		at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
		at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	Caused by: org.apache.maven.plugin.MojoExecutionException: An exception occured while executing the Java class. null
		at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:346)
		at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
		... 19 more
	Caused by: java.lang.reflect.InvocationTargetException
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
		at java.lang.reflect.Method.invoke(Method.java:597)
		at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:291)
		at java.lang.Thread.run(Thread.java:662)
	Caused by: java.lang.NullPointerException
		at java.lang.String$CaseInsensitiveComparator.compare(String.java:1217)
		at java.lang.String$CaseInsensitiveComparator.compare(String.java:1211)
		at java.util.TreeMap.getEntryUsingComparator(TreeMap.java:351)
		at java.util.TreeMap.getEntry(TreeMap.java:322)
		at java.util.TreeMap.get(TreeMap.java:255)
		at org.jvnet.hudson.update_center.LocalDirectoryRepository.listHudsonPlugins(LocalDirectoryRepository.java:132)
		at org.jvnet.hudson.update_center.Main.buildPlugins(Main.java:274)
		at org.jvnet.hudson.update_center.Main.buildUpdateCenterJson(Main.java:203)
		at org.jvnet.hudson.update_center.Main.run(Main.java:167)
		at org.jvnet.hudson.update_center.Main.run(Main.java:144)
		at org.jvnet.hudson.update_center.Main.main(Main.java:131)
		... 6 more
	[ERROR]
	[ERROR]
	[ERROR] For more information about the errors and possible solutions, please read the following articles:
	[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Any idea what could be going on?

**Comment by ikedam** [comment]
Same issue to #16.
