### ISSUE TITLE
Plugin installation gives java.io.IOException error

### ISSUE THREAD

**Issue by Abubakar22** [ikedam/backend-update-center2#26]
I have setup custom plugin update center and when i tried to install the plugins i get the below error. I have tried installing diffferent plugins but i get the same error. Screenshot is attached for the same.

I have used github as a repository and pushed my plugins to github. My Jenkins version is  2.73.3
 
java.io.IOException: Downloaded file /app/jenkins/taaa-deploy/plugins/nant.jpi.tmp does not match expected SHA-1, expected 'Pfm4i25OeWGv2CozWtlYEeEpmf0=', actual 'bijiKp8jlcJXQpUfGOdpnzZ47D4='
	at hudson.model.UpdateCenter.verifyChecksums(UpdateCenter.java:1810)
	at hudson.model.UpdateCenter.access$1100(UpdateCenter.java:149)
	at hudson.model.UpdateCenter$InstallationJob.replace(UpdateCenter.java:1963)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.install(UpdateCenter.java:1194)
	at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1680)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1874)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1651)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
	at java.lang.Thread.run(Thread.java:748)

![update-center1](https://user-images.githubusercontent.com/17588727/33689261-c92b5eb4-daac-11e7-8d0c-ab66d6322baf.JPG)

**Comment by ikedam** [comment]
@Abubakar22 
Here's NOT a customer support.
No one can say anything without the detail of you setup.
If you did wrong setup, everything work wrong.
And why don't you test the content of /app/jenkins/taaa-deploy/plugins/nant.jpi.tmp?
